"""transactions table

Revision ID: c35b2efee107
Revises: 
Create Date: 2019-03-08 11:56:43.587160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35b2efee107'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('potato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variety_name', sa.String(length=128), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('fee', sa.String(length=64), nullable=True),
    sa.Column('variety', sa.String(length=128), nullable=True),
    sa.Column('market_price', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('medium', sa.String(length=128), nullable=True),
    sa.Column('potato_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['potato_id'], ['potato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('potato')
    # ### end Alembic commands ###
